### ISSUE TITLE
Packwiz support

### ISSUE THREAD

**Issue by oatmealine** [Infinidoge/nix-minecraft#12]
[Packwiz](https://packwiz.infra.link/) support would be greatly appreciated, as manually fetching every mod through `fetchModrinth` isn't the best - I'd really like being able to point it at a `pack.toml` URL and have it download the bootstrapper, run it, etc. all on its own.

**Comment by imsofi** [comment]
I am currently working on [packwiz2nix](https://github.com/imsofi/packwiz2nix) tooling for this exact use-case. Its not yet published but will be soon.

For now you could use the imperative way of adding [packwiz-installer-bootstrap](https://github.com/packwiz/packwiz-installer-bootstrap/) to your minecraft server root (`/var/lib/minecraft/`), then inside your NixOS configuration add a `ExecStartPre` to your systemd service file similar to whats described in its [tutorial](https://packwiz.infra.link/tutorials/installing/packwiz-installer/):

> java -jar packwiz-installer-bootstrap.jar -g -s server https://[your-server]/pack.toml

**Comment by oatmealine** [comment]
As an alternative, [unsup](https://git.sleeping.town/unascribed/unsup) has worked quite well for me and supports the Packwiz format:

```nix
let
  # https://git.sleeping.town/unascribed/unsup/releases
  unsup = pkgs.fetchurl {
    url = "https://git.sleeping.town/attachments/c521d178-8938-40a5-b21b-0333eef4099e";
    sha256 = "c5bd49784392b651e4bc71fe57976f5b4fb14f09e0e23183ae5b94a821ae4756";
  };
  packLocation = "https://example.com/pack.toml";
  unsupIni = ''
    version=1
    preset=minecraft

    source_format=packwiz
    source=${packLocation}

    force_env=server
    no_gui=true

    [flavors]
    shaders=no_shaders
  '';
in {
  # ...
  symlinks = {
    "unsup.ini" = pkgs.writeTextFile {
      name = "unsup.ini";
      text = unsupIni;
    };
  };
  jvmOpts = "-Xmx4G -javaagent:${unsup}"
}
```

**Comment by Infinidoge** [comment]
If `fetchPackwizModpack` isn't sufficient, this issue can be reopened if necessary.

**Comment by TheAyes** [comment]
I would like to add an request here as I think it might be fitting.

In my use case I manage a Server for my friends, I would like to manage the Modpack via packwiz. Since in my case I'm basing my modpack off of an existing modpack I would need a way to either:
- Run the Packwiz installer instead of the server jar (which downloads the mods and boots up the server afterwards)
- Have a way to fetch the modpack (probably using fetchPackwizModpack) into the mods folder while allowing new mods to be added afterwards
- Or (probably the worst approach of all) have a mixed declarative/imperative option that allows me to add the mods from the modpack manually, while doing modifications via nix.

**Comment by Infinidoge** [comment]
So far, the best experience I've had is with using [unsup](https://git.sleeping.town/unascribed/unsup/) as a JavaAgent, and managing mods outside of Nix entirely, instead letting unsup fetch from a packwiz pack.
