### ISSUE TITLE
Code from nix-minecraft-servers

### ISSUE THREAD

**Issue by jyooru** [Infinidoge/nix-minecraft#23]
Hi there! I've deprecated my flake [nix-minecraft-servers](https://github.com/jyooru/nix-minecraft-servers/blob/main/packages/waterfall/default.nix) as I no longer want to continue maintaining it. I'm wondering if you'd like to take any code from it? I can see you already have most server packages, but there are a few proxies like Velocity and Waterfall that you are welcome to have.

**Comment by Infinidoge** [comment]
Hello! I haven't done much with proxies like Velocity and Waterfall, so I don't personally have much experience working with them,
That being said, since the goal of this project is to package what is possible, I'll certainly look into including them into the repository. (And likely also adding Purpur to go along side Paper)
I'll certainly keep your repository in mind for those.

(I am also happy that people seem to like this repository :)

**Comment by Infinidoge** [comment]
Velocity is being handled by #25.

**Comment by Infinidoge** [comment]
I've gone ahead and opened #36 and #37 about packaging Waterfall and Purpur respectively, which are the two things left that differ between the two projects. I'm going ahead and closing this issue in favor of the two new issues.
